version: '3.7'

services:
  democlean.webapi:
    container_name: democleanwebapi
    image: ${DOCKER_REGISTRY-}democleanarchitecturewebapi
    build:
      context: .
      dockerfile: DemoCleanArchitecture.WebApi/vscode.dockerfile
      target: debug
    environment:
       DEMOCLEAN_CONN: Host=democlean.database;Port=5432;Database=DemoClean;User Id=postgres;Password=postgres;
    volumes:
      - ../DemoCleanArchitecture:/src
      #- ../../../:/root/debug
      - ../:/root/debug
    ports:
      - 5000:5000
    networks:
      - democleanarchitecture-network
    depends_on:
      - democlean.database  

  democlean.database:
    image: postgres:9.5
    restart: always
    environment:  
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - democleanarchitecture-network

volumes:  
  pgdata:       

networks: 
  democleanarchitecture-network: